### PR TITLE
[depends] add libraw 0.18.2

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by akva2** [comment]
i cannot merge this. it will break pkgconfig platforms - PC_RAW_INCLUDEDIR includes libraw/

**Comment by Rechi** [comment]
Please give me an example of such a platform.
snippet from debians pc file: `includedir=${prefix}/include`

**Comment by akva2** [comment]
you are on such a platform. includedir is an internal variable, it's not the stuff that is exposed. ref

```
akva@akvarium:~/kode/opm/sibling/opm-core$ pkg-config --cflags-I-only libraw_r
-I/usr/include/libraw
```
and from pc file:
Cflags: -I${includedir}/libraw

**Comment by Rechi** [comment]
updated
I was already for the functionality `PATH_SUFFIXES` does.
Is it correct now?

**Comment by notspiff** [comment]
yup. unless you have more i will merge

**Comment by Rechi** [comment]
Please merge this now.
Have no additional changes yet,.

**Pull request merged**
